import { Inter } from "next/font/google";
import "./globals.css";
import { MyProvider } from '../app/context/MyProvider';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Momentary",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <MyProvider>
        <body className={inter.className}>{children}</body>
      </MyProvider>
    </html >
  );
}
